name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Validate JSON schemas
      run: |
        sudo npm install --global ajv-cli
        ajv compile -s src/*.schema.json
